Models/Usuarios.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Simbora04.Models
{
    [Table("Usuarios")]
    public class Usuarios
    {
		[Key]
		public int Id { get; set; }

		[Display(Name = "Email")]
		[Required(ErrorMessage = "Obrigatório informar o email")]
		public string Nome { get; set; }

		[Display(Name = "Senha")]
		[Required(ErrorMessage = "Obrigatório informar a senha")]
		[DataType(DataType.Password)]
        public string Senha { get; set; }

	}
}

Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Simbora04.Models;

namespace Simbora04.Controllers
{
    public class EventosController : Controller
    {
        private readonly Contexto _context;

        public EventosController(Contexto context)
        {
            _context = context;
        }

        // GET: Eventos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Evento.ToListAsync());
        }

        // GET: Eventos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // GET: Eventos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Data,Horario,Local,Degraca")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.FindAsync(id);
            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Data,Horario,Local,Degraca")] Evento evento)
        {
            if (id != evento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Evento.FindAsync(id);
            _context.Evento.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventoExists(int id)
        {
            return _context.Evento.Any(e => e.Id == id);
        }
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Simbora04.Models;
namespace Simbora04.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly Contexto _context;

        public UsuariosController(Contexto context)
        {
            _context = context;
        }
        
        
        [HttpPost]
        public async Task<IActionResult> Logar([Bind("Id, Senha")] Usuarios usuarios)
        {
            var user = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == usuarios.Id);
            if (user == null)
            {
                ViewBag.Message = "Usuario e/ou senha inválidos!";
                return View();
            }
            bool senhaOK = BCrypt.Net.BCrypt.Verify(usuarios.Senha, user.Senha);
            if (senhaOK)
            {
                return View();
            }

            return View();

        }



















        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuario.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        public IActionResult ContaJaExiste()
        {
            return View();
        }

        public IActionResult CadastroFeito()
        {
            return View();
        }

        public IActionResult Perfil()
        {
            return View();
        }



        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Senha")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                
                _context.Add(usuarios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ContaJaExiste));
            }
            return View(usuarios);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuario.FindAsync(id);
            if (usuarios == null)
            {
                return NotFound();
            }
            return View(usuarios);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Senha")] Usuarios usuarios)
        {
            if (id != usuarios.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuarios);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuariosExists(usuarios.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuarios);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuarios = await _context.Usuario.FindAsync(id);
            _context.Usuario.Remove(usuarios);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuariosExists(int id)
        {
            return _context.Usuario.Any(e => e.Id == id);
        }
    }
}

Views/Usuarios/CadastroFeito.cshtml
@model Simbora04.Models.Usuarios

@{
    ViewData["Title"] = "CadastroFeito";
}


<head>

    <link rel="stylesheet" href="/css/cadastroConcluido.css" />
</head>
<body>

    <div class="loginbox">
        <h1 style="color: #FF7575">Cadastro Concluído!</h1>
        <a class"btn btn-primary" asp-controller="Eventos" asp-action="Index" style=" border: none; outline: none; height: 40px; background: #FF7575; color: #fff; font-size: 18px; border-radius: 20px; margin-top: 20px;">Ver Eventos</a>
        <a class"btn btn-primary" asp-controller="Eventos" asp-action="Create" style=" border: none; outline: none; height: 40px; background: #FF7575; color: #fff; font-size: 18px; border-radius: 20px; margin-top: 20px;">Criar Eventos!</a>
        <a class="btn btn-primary" asp-controller="Usuarios" asp-action="ContaJaExiste" style=" border: none; outline: none; height: 40px; background: #FF7575; color: #fff; font-size: 18px; border-radius: 20px; margin-top: 20px;">Voltar</a>
    </div>
</body>

Views/Usuarios/ContaJaExiste.cshtml
@model Simbora04.Models.Usuarios
@{
    ViewData["Title"] = "ContaJaExiste";
}
<head>

    <link rel="stylesheet" href="/css/ContaJaExisteStyle.css" />
</head>
<body>

    <div class="loginbox">

        <div class="col-md-4">
            <form asp-action="Create" class="center">
                <h1>Entrar</h1>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" style="width: 220px;">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group" style="width: 220px;">
                    <label asp-for="Senha" class="control-label"></label>
                    <input asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-primary" asp-controller="Eventos" asp-action="Index" style=" border: none; outline: none; height: 40px; background: #FF7575; color: #fff; font-size: 18px; border-radius: 20px; margin-top: 20px; width: 220px;">Entrar</a>
                         <a class="btn btn-primary" asp-action="Create" style="border: none; outline: none; height: 40px; background: #FF7575; color: #fff; font-size: 18px; border-radius: 20px; margin-top: 20px; width: 220px;">Voltar</a>
                </div>
            </form>

        </div>
    </div>
       
</body>

Views/Usuarios/Create.cshtml
@model Simbora04.Models.Usuarios

@{
    ViewData["Title"] = "Create";
}
<head>

    <link rel="stylesheet" href="/css/Usuarios.css" />
</head>
<body>

    <div class="loginbox">
        
        <div class="col-md-4">
              <form asp-action="Create" class="center">
                    <h1 style="width: 220px;">Cadastre-se!</h1>
                      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                      <div class="form-group" style="width: 220px;">
                          <label asp-for="Nome" class="control-label"></label>
                          <input asp-for="Nome" class="form-control" />
                          <span asp-validation-for="Nome" class="text-danger"></span>
                      </div>
                      <div class="form-group" style="width: 220px;">
                          <label asp-for="Senha" class="control-label"></label>
                          <input asp-for="Senha" class="form-control" />
                          <span asp-validation-for="Senha" class="text-danger"></span>
                      </div>
                      <div class="form-group">
                          <input type="submit" value="Criar conta!" class="btn btn-primary" asp-controller="Usuarios" asp-action="CadastroFeito" />
                          <a class="btn btn-primary" asp-controller="Usuarios" asp-action="ContaJaExiste" style=" border: none; outline: none; height: 40px; background: #FF7575; color: #fff; font-size: 18px; border-radius: 20px; margin-top: 20px;">Já tenho conta!</a>
                          
                      </div>
                  </form>
              
        </div>
    </div>

 

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>

Views/Usuarios/Delete.cshtml
@model Simbora04.Models.Usuarios

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuarios</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Usuarios/Details.cshtml
@model Simbora04.Models.Usuarios

@{
    ViewData["Title"] = "Details";
}
<head>

    <link rel="stylesheet" href="/css/usuariosDetails.css" />
</head>
<h1>Details</h1>

<div>
    <h4>Usuarios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Usuarios/Edit.cshtml
@model Simbora04.Models.Usuarios

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usuarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuarios/Index.cshtml
@model IEnumerable<Simbora04.Models.Usuarios>

@{
    ViewData["Title"] = "Index";
}

@foreach (var item in Model)
{
    <div class="loginbox">
        <h1>Bem vindo @Html.DisplayNameFor(model => model.Nome)!</h1>
    
    
    
    
    
    </div>






        }





        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Senha)
                    </th>
                    <th></th>
                </tr>
            </thead>




            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Senha)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

Views/Usuarios/Perfil.cshtml
@page

@model Simbora04.Models.Usuarios
@{
}
<head>
    <link rel="stylesheet" href="/css/perfilUsuarios.css" />
</head>

<body>
    <div class="loginbox">
        <h1> Bem vindo, @Html.DisplayFor(model => model.Nome)</h1>







    </div>


</body>